#pragma config(Motor,  port2,           rightMotor,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           conveyorMotor, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------*\
|*                       	- Joystick Control with Turbo- 1 Remote -                            	*|
|*                                  	ROBOTC on VEX 2.0 Cortex                                  	*|
|*                                                                                                	*|
|*  	                                                                                            *|
|*                                                                                                	*|
|*                                    	ROBOT CONFIGURATION                                     	*|
|*	NOTES:                                                                                      	*|
|*	1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                         	*|
|*	2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                          	*|
|*                                                                                                	*|
|*	MOTORS & SENSORS:                                                                           	*|
|*	[I/O Port]          	[Name]          	[Type]          	[Description]               	*|
|*	Motor - Port 2      	rightMotor       	VEX Motor       	Right motor                 	*|
|*	Motor - Port 3      	leftMotor        	VEX Motor       	Left motor                  	*|
|*	Motor - Port 4      	armMotor         	VEX Motor       	Arm motor                   	*|
|*	Motor - Port 5      	arm2Motor        	VEX Motor       	Arm Motor                   	*|
\*--------------------------------------------------------------------------------------------------*/
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()

{
  while(1 == 1)
{
//don?t worry about this just don?t change it




//currently armMotor and arm2Motor are not being used in this program

//buttons are programmed by Btn then the button group which is labelled on the controller then
//U for up     D for down     L for left     or R for right
//ex. Btn8L would be the button where the X button is on an xbox 360 controller


//to use the second controller for joysticks or buttons,
//just add Xmtr2 to the end of the stuff in the brackets
//ex. vexRT[Btn6UXmtr2]   means button 6U on the 2nd controller
//ex. vexRT[Ch3Xmtr2] means the ch3 (Y axis) on the left joystick on the 2nd controller




//NORMAL DRIVE SPEED W/O TURBO
  float currentpwr = .6;
	//the normal speed for the robot without the turbo button is currently sending 60% power to the drive motors
    //if the robot is too fast without the turbo button, decrease this number
    //if the robot is too slow without the turbo button, increase this number but know that there will be no increase in the turbo speed



//current power is normally set at 60% but when button 5U is pressed, current power is set
//to 100%, full motor output
	if (vexRT[Btn6U] == 1)
		//5U can be replaced with 5D, 6U, or 6D depending on where you want
    	//the turbo button (left or right trigger and upper or lower)
		//currently it is the top left trigger, the button labelled 5U


//TURBO BUTTON PWR
{
  	currentpwr = 1;
  	//if for some reason mechanical do their job way too well and 100% pwr to the motors is way too fast for the turbo button then you can decrease this number
  	//contrary to popular belief, the turbo button does not give the motors "extra speed," it just doesn't deny them full power
  	//this number cannot go over 1, we can't send like 500% pwr to the motors, sorry mechanical team, that's your job to fix the gear ratio
    //you cannot increase the speed of the robot past the turbo button speed if the turbo button speed is set at 1
	}

if (vexRT[Btn6D] == 1)

{
	currentpwr = 0.3;
}



//DRIVE TRAIN
  //driving with RIGHT joystick only
  //turbo
	//motor[leftMotor]  = currentpwr*((vexRT[Ch2] + vexRT[Ch1])/2);  // (y + x)/2
	//motor[rightMotor] = currentpwr*((vexRT[Ch2] - vexRT[Ch1])/2);  // (y - x)/2


  //driving with RIGHT joystick only
  //no turbo
	//motor[leftMotor]  =(vexRT[Ch2] + vexRT[Ch1])/2;  // (y + x)/2
	//motor[rightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;  // (y - x)/2

 //driving with LEFT joystick only
 //turbo button
  	motor[leftMotor]  = currentpwr*((vexRT[Ch3] + vexRT[Ch4])/2);  // (y + x)/2
  	motor[rightMotor] = currentpwr*((vexRT[Ch3] - vexRT[Ch4])/2);  // (y - x)/2
			//motor[leftMotor] = currentpwr*(vexRT[Ch3]);
			//motor[rightMotor] = currentpwr*(vexRT[Ch2]);

//driving with LEFT joystick only
//no turbo button
  	//motor[leftMotor]  = (vexRT[Ch3] + vexRT[Ch4])/2;  // (y + x)/2
  	//motor[rightMotor] = (vexRT[Ch3] - vexRT[Ch4])/2;  // (y - x)/2


//tank drive with 2 joysticks, LEFT motor Left joystick and RIGHT motor RIGHT joystick
//turbo button
  	//motor[leftMotor] = currentpwr*(vexRT[Ch3] / 2);
  	//motor[rightMotor] = currentpwr*(vexRT[Ch2] / 2);


//tank drive with 2 joysticks, LEFT motor Left joystick and RIGHT motor RIGHT joystick
//no turbo button
  	//motor[leftMotor] = vexRT[Ch3] / 2;
  	//motor[rightMotor] = vexRT[Ch2] / 2;




		if (vexRT[Btn5UXmtr2] == 1)

{
		motor[intakeMotor]=127;
}

  else

{
    motor[intakeMotor]=0;
}


	if (vexRT[Btn5DXmtr2] == 1)
{
	motor[intakeMotor]=-127;
}

	else

{
	motor[intakeMotor]=0;
}


	if (vexRT[Btn6UXmtr2] == 1)

{
	motor[conveyorMotor]=127;
}

	else

{
	motor[conveyorMotor]=0;


	if (vexRT[Btn6DXmtr2] == 1)

{
	motor[conveyorMotor]=-127;
}

	else

{
	motor[conveyorMotor]=0;

}}
}}
